## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from tensorflow.keras.layers import Input, Dense

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [4]:
# Create a list of at least 10 column names to use as X data
selected_columns = ['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime', 'StockOptionLevel',
                    'WorkLifeBalance', 'YearsAtCompany', 'YearsSinceLastPromotion', 'NumCompaniesWorked']

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]

# Show the data types for X_df
print(X_df.dtypes)

Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object


In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split



In [6]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.3, random_state=69)

In [7]:
# Convert X data to numeric
X_train['OverTime'] = X_train['OverTime'].apply(lambda x: 1 if x == 'Yes' else 0)
X_test['OverTime'] = X_test['OverTime'].apply(lambda x: 1 if x == 'Yes' else 0)

In [8]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_train_scaled = scaler.fit_transform(X_train)

# Scale the training and testing data
X_test_scaled = scaler.transform(X_test)

In [9]:
# Create a OneHotEncoder for the Department column
encoder_dept = OneHotEncoder(sparse=False)

# Fit the encoder to the training data
encoder_dept.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dept_encoded = encoder_dept.transform(y_train[['Department']])
y_test_dept_encoded = encoder_dept.transform(y_test[['Department']])

print("Encoded Department - Training Data:")
print(y_train_dept_encoded[:5])
print("Encoded Department - Testing Data:")
print(y_test_dept_encoded[:5])

Encoded Department - Training Data:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
Encoded Department - Testing Data:
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [10]:
# Create a OneHotEncoder for the Attrition column
encoder_attrition = OneHotEncoder(sparse=False)

# Fit the encoder to the training data
encoder_attrition.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
y_train_attrition_encoded = encoder_attrition.transform(y_train[['Attrition']])
y_test_attrition_encoded = encoder_attrition.transform(y_test[['Attrition']])

print("Encoded Attrition - Training Data:")
print(y_train_attrition_encoded[:5])
print("Encoded Attrition - Testing Data:")
print(y_test_attrition_encoded[:5])

Encoded Attrition - Training Data:
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
Encoded Attrition - Testing Data:
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


## Create, Compile, and Train the Model

In [11]:
# Find the number of columns in the X training data
n_features = X_train_scaled.shape[1]

# Create the input layer
input_layer = Input(shape=(n_features,), name='input')

# Create at least two shared layers
shared1 = Dense(64, activation='relu', name='shared1')(input_layer)
shared2 = Dense(128, activation='relu', name='shared2')(shared1)

In [12]:
# Create a branch for Department
# with a hidden layer and an output layer
# Create the hidden layer
department_hidden = Dense(32, activation='relu', name='department_hidden')(shared2)

# Create the output layer
department_output = Dense(y_train_dept_encoded.shape[1], activation='softmax', name='department_output')(department_hidden)

In [13]:
# Create a branch for Attrition
# with a hidden layer and an output layer
# Create the hidden layer
attrition_hidden = Dense(32, activation='relu', name='attrition_hidden')(shared2)

# Create the output layer
attrition_output = Dense(2, activation='sigmoid', name='attrition_output')(attrition_hidden)

In [14]:
# Create the model
model = Model(inputs=input_layer, outputs=[department_output, attrition_output], name='attrition_model')

# Compile the model
model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'binary_crossentropy'},
              metrics={'department_output': 'accuracy', 'attrition_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "attrition_model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input (InputLayer)          [(None, 10)]                 0         []                            
                                                                                                  
 shared1 (Dense)             (None, 64)                   704       ['input[0][0]']               
                                                                                                  
 shared2 (Dense)             (None, 128)                  8320      ['shared1[0][0]']             
                                                                                                  
 department_hidden (Dense)   (None, 32)                   4128      ['shared2[0][0]']             
                                                                                    

In [15]:
# Train the model
history = model.fit(
    x=X_train_scaled,
    y={'department_output': y_train_dept_encoded, 'attrition_output': y_train_attrition_encoded},
    batch_size=32,
    epochs=100,
    verbose=1,
    validation_data=(X_test_scaled, {'department_output': y_test_dept_encoded, 'attrition_output': y_test_attrition_encoded})
)

Epoch 1/100
33/33 [==============================] - 6s 40ms/step - loss: 1.3296 - department_output_loss: 0.8315 - attrition_output_loss: 0.4981 - department_output_accuracy: 0.6327 - attrition_output_accuracy: 0.8552 - val_loss: 1.3244 - val_department_output_loss: 0.8174 - val_attrition_output_loss: 0.5070 - val_department_output_accuracy: 0.6485 - val_attrition_output_accuracy: 0.8027
Epoch 2/100
33/33 [==============================] - 1s 15ms/step - loss: 1.1692 - department_output_loss: 0.7650 - attrition_output_loss: 0.4043 - department_output_accuracy: 0.6569 - attrition_output_accuracy: 0.8542 - val_loss: 1.2781 - val_department_output_loss: 0.8132 - val_attrition_output_loss: 0.4649 - val_department_output_accuracy: 0.6485 - val_attrition_output_accuracy: 0.8027
Epoch 3/100
33/33 [==============================] - 0s 15ms/step - loss: 1.1356 - department_output_loss: 0.7531 - attrition_output_loss: 0.3824 - department_output_accuracy: 0.6550 - attrition_output_accuracy: 0.85

In [16]:
# Attempt to train the model again
history = model.fit(
    x=X_train_scaled,
    y={'department_output': y_train_dept_encoded, 'attrition_output': y_train_attrition_encoded},
    batch_size=32,
    epochs=100,
    verbose=1,
    validation_data=(X_test_scaled, {'department_output': y_test_dept_encoded, 'attrition_output': y_test_attrition_encoded})
)

Epoch 1/100
33/33 [==============================] - 0s 9ms/step - loss: 0.0342 - department_output_loss: 0.0278 - attrition_output_loss: 0.0064 - department_output_accuracy: 0.9961 - attrition_output_accuracy: 1.0000 - val_loss: 4.6575 - val_department_output_loss: 3.0678 - val_attrition_output_loss: 1.5897 - val_department_output_accuracy: 0.5601 - val_attrition_output_accuracy: 0.7914
Epoch 2/100
33/33 [==============================] - 0s 5ms/step - loss: 0.0377 - department_output_loss: 0.0307 - attrition_output_loss: 0.0070 - department_output_accuracy: 0.9961 - attrition_output_accuracy: 1.0000 - val_loss: 4.6535 - val_department_output_loss: 3.0037 - val_attrition_output_loss: 1.6498 - val_department_output_accuracy: 0.5420 - val_attrition_output_accuracy: 0.8005
Epoch 3/100
33/33 [==============================] - 0s 5ms/step - loss: 0.0363 - department_output_loss: 0.0299 - attrition_output_loss: 0.0064 - department_output_accuracy: 0.9961 - attrition_output_accuracy: 1.0000 

In [17]:
# Evaluate the model with the testing data
# Evaluate the model on the testing data
evaluation_results = model.evaluate(
    x=X_test_scaled,
    y={'department_output': y_test_dept_encoded, 'attrition_output': y_test_attrition_encoded},
    verbose=1
)

14/14 [==============================] - 0s 2ms/step - loss: 5.9138 - department_output_loss: 3.9398 - attrition_output_loss: 1.9741 - department_output_accuracy: 0.5488 - attrition_output_accuracy: 0.7937


In [18]:
# Print the accuracy for both department and attrition
department_accuracy = evaluation_results[-2]
attrition_accuracy = evaluation_results[-1]

print(f"Department predictions accuracy: {department_accuracy}")
print(f"Attrition predictions accuracy: {attrition_accuracy}")

Department predictions accuracy: 0.5487528443336487
Attrition predictions accuracy: 0.7936508059501648


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

Accuracy can be a useful metric for getting a general sense of model performance, especially when the classes in the dataset are balanced. However, it might not be the best metric in all cases, particularly for imbalanced datasets where one class significantly outnumbers the other.

For the 'Department' classification, if the distribution of classes is relatively balanced, accuracy might give a reasonable measure of performance. However, if some departments are much less common than others, accuracy could be misleading.

For the 'Attrition' prediction, if the number of employees leaving is much lower than those staying, then accuracy might not reflect the model's ability to correctly identify the less frequent class. In such cases, other metrics like precision, recall, F1 score, and ROC AUC could provide more insight into model performance, especially for identifying true positives and handling false negatives.

2. What activation functions did you choose for your output layers, and why?

For the 'Department' output, a softmax activation function was chosen because it's a multi-class classification problem. Softmax is suitable for these types of problems because it converts the output scores from the model into probabilities by comparing the score for each class relative to the scores for other classes. This allows the model to output a probability distribution over the classes.

For the 'Attrition' output, initially, a sigmoid activation function was suggested, typical for binary classification tasks, as it outputs a probability score between 0 and 1, indicating the likelihood of the sample belonging to a positive class. To accommodate the one-hot encoded 'Attrition' data, softmax was used. This was suitable because it also handles the 'Attrition' prediction as a case of multi-class classification with two classes.

3. Can you name a few ways that this model might be improved?

Data Preprocessing: Better feature engineering, such as creating new features or selecting features more carefully, might improve model performance. Additionally, addressing class imbalance through techniques like SMOTE or adjusting class weights in the model training could help.

Model Architecture: Experimenting with different architectures, such as varying the number and size of layers, or using regularization techniques like dropout to prevent overfitting, might yield improvements.

Hyperparameter Tuning: Adjusting hyperparameters, including the learning rate, batch size, and epochs, through systematic search methods or automated methods could lead to better performance.